"""modified billing details

Revision ID: 39662ab7a33e
Revises: dda791924f21
Create Date: 2024-08-12 02:32:44.336340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39662ab7a33e'
down_revision = 'dda791924f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_details', schema=None) as batch_op:
        batch_op.drop_constraint('fk_billing_details_order_id_orders', type_='foreignkey')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_billing_detail_id_billing_details', type_='foreignkey')
        batch_op.drop_column('billing_detail_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_detail_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_orders_billing_detail_id_billing_details', 'billing_details', ['billing_detail_id'], ['id'])

    with op.batch_alter_table('billing_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_billing_details_order_id_orders', 'orders', ['order_id'], ['id'])

    # ### end Alembic commands ###
