"""renamed a column in SearchQuery

Revision ID: f0f9e79944d7
Revises: 99b7ab10cbaa
Create Date: 2024-08-01 21:34:29.994295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f9e79944d7'
down_revision = '99b7ab10cbaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_query', sa.String(length=200), nullable=True))
        batch_op.drop_column('query')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('search_query')

    # ### end Alembic commands ###
